<?php
  function dbSeed(){
    include 'connection.php';
    connect();
    
    // this clears entire database
    $reset = "TRUNCATE TABLE movies";
    $run = mysql_query($reset) or die(mysql_error());

    // seed sample reviews
    $sample1 = "INSERT INTO `movies` (`movie_title`, `overview`, `director`, `cast`, `poster_path`, `backdrop_path`, `score`, `review`, `release_date`, `publish_date`, `featured`, `popular_vote`, `genre`)
  VALUES
    ('The Martian', 'During a manned mission to Mars, Astronaut Mark Watney is presumed dead after a fierce storm and left behind by his crew. But Watney has survived and finds himself stranded and alone on the hostile planet. With only meager supplies, he must draw upon his ingenuity, wit and spirit to subsist and find a way to signal to Earth that he is alive.', 'Ridley Scott', '1892, 83002, 41091', '/assets/images/posters/3d3216400033479af074d851a8f49de171faf27d.jpg', '/assets/images/backdrops/63fae34794bbc819ded9e5ba5707b8bb3cb3d062.jpg', 5, 'Ridley is no stranger to space or sci-fi movies. In fact its a realm he excels in better than any other. His practice and experience dealing with the universe is something untouched by any other. And there could have been no better director for this movie. And with time his movies have only gotten better, the cinematography is without a doubt getting better and better with each film he puts out.\r\n\r\nCasting Damon only solidified this movie into a 5 star. With his lighthearted approach and witty characteristics he really made you feel for Watney. Everyone wanted to see him make it home just as much as he wanted to get home.\r\n\r\nI love walking away from this movie knowing that I have another movie from Scott that I can sit down and watch at any given moment, and enjoy it just as much as I did the first time around.', '2015-09-30', '2016-03-04', 1, '7.6', 'Drama, Adventure, Science Fiction')";

    $sample2 = "INSERT INTO `movies` (`movie_title`, `overview`, `director`, `cast`, `poster_path`, `backdrop_path`, `score`, `review`, `release_date`, `publish_date`, `featured`, `popular_vote`, `genre`)
  VALUES
    ('Alien', 'During its return to the earth, commercial spaceship Nostromo intercepts a distress signal from a distant planet. When a three-member team of the crew discovers a chamber containing thousands of eggs on the planet, a creature inside one of the eggs attacks an explorer. The entire crew is unaware of the impending nightmare set to descend upon them when the alien parasite planted inside its unfortunate host is birthed.', 'Ridley Scott', '10205, 4139, 5047', '/assets/images/posters/694c14c7cdb21487e17a76240ee9a016c7121b7f.jpg', '/assets/images/backdrops/672fdaf7f4cd74818906b1afd630e7d436917c7a.jpg', 5, 'I remember being a child when this movie was on TV and my parents made me go to bed instead of staying up late to watch it.\r\n\r\nI immediately snuck into their bedroom and watched it there instead of the living room. And I had nightmares for weeks. The work Giger did creating the atmosphere of this movie was magnificent. There\'s really something to be said about doing something right the first time and it lasting.\r\n\r\nScott\'s power in space and sci-fi finding its stride with this movie and setting the tone for his future as well as mine. This franchise remains to be one of my absolute favorites. Finding a good sci-fi horror movie with a unique and original creature is a rare this. And they nailed it perfectly with Alien(s).', '1979-05-25', '2016-03-05', NULL, '7.5', 'Horror, Action, Thriller, Science Fiction')";

    $sample3 = "INSERT INTO `movies` (`movie_title`, `overview`, `director`, `cast`, `poster_path`, `backdrop_path`, `score`, `review`, `release_date`, `publish_date`, `featured`, `popular_vote`, `genre`)
  VALUES
    ('Deadpool', 'Based upon Marvel Comics most unconventional anti-hero, DEADPOOL tells the origin story of former Special Forces operative turned mercenary Wade Wilson, who after being subjected to a rogue experiment that leaves him with accelerated healing powers, adopts the alter ego Deadpool. Armed with his new abilities and a dark, twisted sense of humor, Deadpool hunts down the man who nearly destroyed his life.', 'Tim Miller', '10859, 54882, 51990', '/assets/images/posters/512bc74b7c68b4270ccf7360094b8ff6d8b947b4.jpg', '/assets/images/backdrops/b8ded672350dbadb4155f5f550d74fcedb2ebd9a.jpg', 4, 'I put off seeing this one. I really did. I just didn\'t think at all I\'d care for this character. I didn\'t really know his story and maybe I was just turned off by the hype around it.\r\n\r\nSo at lunch me and the girl are trying to figure out what movie to see that evening and I was pushing for Hail, Ceasar! But we just couldn\'t find any good showtimes. She brought up Deadpool and I immediately shot it down, however, there was a perfect pair of seats. At the perfect showtime. At the theater right by me...\r\n\r\nSo convenience won...\r\n\r\nWith that all being said, here we go! I loved this movie! It was delightful! I mean it had the perfect amount of sass and action and weird goofy cleverness. And the humor let\'s be perfectly honest with each other here; aligned perfectly with my sense of humor. So, this movie, absolutely, go see. Enjoy it. Love it. It was wonderful.', '2016-02-09', '2016-03-05', NULL, '7.3', 'Adventure, Action, Comedy')";

    $sample4 = "INSERT INTO `movies` (`movie_title`, `overview`, `director`, `cast`, `poster_path`, `backdrop_path`, `score`, `review`, `release_date`, `publish_date`, `featured`, `popular_vote`, `genre`)
  VALUES
    ('Spy Game', 'Veteran spy Nathan Muir is on the verge of retiring from the CIA when he learns that his one-time protg and close friend, Tom Bishop, is a political prisoner sentenced to die in Beijing. Although their friendship has been marred by bad blood and resentment, Muir agrees to take on the most dangerous mission of his career and rescue Bishop.', 'Tony Scott', '4135, 287, 2462', '/assets/images/posters/171912c1a457c606277669ba21aa517eb44bb6c6.jpg', '/assets/images/backdrops/7fef0439d9d87e4e3f957b1be014d798181c95c3.jpg', 4, 'As Brad Pitt climbs up into the spy world from the help of his mentor Robert Redford. Pitts character Bishop falls into the hands of China after a rescue op gone wrong. And as he\'s walking out the door for retirement, Redford\'s character Muir picks up wind of his boys situation and agrees to hold back for the day to help him out.\r\n\r\nRedford does a great job of twisting the scene to his will, he\'s always moving 5 steps ahead of everyone else to save his boy Pitt. Retelling one of the best spy stories I\'ve seen on screen yet.\r\n\r\nHe\'s a storyteller and a wonderful one at that. This movie sits at the top of all spy movies for sure. It holds me for its story and its action. The balance between shifting the scene with Redford and Pitt is amazing.', '2001-11-18', '2016-03-05', NULL, '6.4', 'Action, Crime, Thriller')";

    $sample5 = "INSERT INTO `movies` (`movie_title`, `overview`, `director`, `cast`, `poster_path`, `backdrop_path`, `score`, `review`, `release_date`, `publish_date`, `featured`, `popular_vote`, `genre`)
  VALUES
    ('Blade Runner', 'In the smog-choked dystopian Los Angeles of 2019, blade runner Rick Deckard is called out of retirement to kill a quartet of replicants who have escaped to Earth seeking their creator for a way to extend their short life spans.', 'Ridley Scott', '3, 585, 586', '/assets/images/posters/847d0244ffd9d8a9c377477d89f12215b46de738.jpg', '/assets/images/backdrops/b19b8572fc0ccd590f471d3a4240554d3a88d1f7.jpg', 5, 'This is a hard movie for me to review... It\'s my number one all time favorite movie, and I don\'t see it getting knocked down anytime soon... I could probably write for days on end about this one but I\'m trying to keep these short and sweet, no one wants to read a novel here. Especially by me.\r\n\r\nHarrison Ford does a perfect job setting the tune for this movie as Deckard. Now also let me make it clear I\'m talking about the final cut, not the theatrical cut. He\'s not a narrator lets be honest with each other. He keeps his character very lo-fi throughout the entirety of the movie. The way he reacts and displays his disdain for the line of Blade Running. But its a job that has to be done. \"If you\'re not cop you\'re little people.\" Retiring androids to him teeter totters on the line of killing humans. It\'s hard to tell which is which in his line of duty.\r\n\r\nScott does the best job here setting up a futuristic dystopian-like world where humans co-exist with androids. The movie rarely sheds light on the scene and Scott keeps the movie dark to hold fast with the mood of everything. \r\n\r\nI could go into the music of this movie - but the best way to put this is just as simple as the soundtrack itself. Perfect. Not only does it help set the mood for the movie but it also helps carry it deeper and deeper into the darkness.\r\n\r\nThis is a movie I could sit and watch every day of the week in the dark and be perfectly content with my life after it all. I know this, because I\'ve done it and still do. This movie is the reason why I\'m doing this now. I think its a crime to live a life without having seen Blade Runner.\r\n\r\n', '1982-06-25', '2016-03-05', NULL, '7.6', 'Science Fiction, Drama, Thriller')";

    $sample6 = "INSERT INTO `movies` (`movie_title`, `overview`, `director`, `cast`, `poster_path`, `backdrop_path`, `score`, `review`, `release_date`, `publish_date`, `featured`, `popular_vote`, `genre`)
  VALUES
    ('The Dark Knight', 'Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations that plague the streets. The partnership proves to be effective, but they soon find themselves prey to a reign of chaos unleashed by a rising criminal mastermind known to the terrified citizens of Gotham as the Joker.', 'Christopher Nolan', '3894, 1810, 6383', '/assets/images/posters/66e14c4a71a75a03abe4cfae5c9d5c0e1ef4964a.jpg', '/assets/images/backdrops/a75e9f654c70088e67f4a38d1ac70f73beb26b09.jpg', 5, 'I think we all know where this is going. Yadda yadda yadda about Ledgers performance as the Joker. But I just want to say without Bale to carry the intensity I think this movie would have gotten away from itself. And with recent light on Bale saying he didn\'t \"quite nail the part\" as Batman I want say to him.\r\n\r\nYou\'re wrong. You did.\r\n\r\nI\'ve watched all the Batman movies to this day and without a doubt he\'s the best.\r\n\r\nI think Bale keeps this movie going at a solid 4, his power and his intensity is like a semi truck. I don\'t think theres very many movies you can get up to go use the bathroom during. It just keeps killing it nonstop.\r\n\r\nBut, with that being said, it wouldn\'t have hopped into a 5 without Ledger. And to be frank here just a movie about the Joker would still be pretty cool to watch. In fact why don\'t they make movies where the lead is the villain?', '2008-07-16', '2016-03-05', NULL, '8', 'Drama, Action, Crime, Thriller')";

    $sample7 = "INSERT INTO `movies` (`movie_title`, `overview`, `director`, `cast`, `poster_path`, `backdrop_path`, `score`, `review`, `release_date`, `publish_date`, `featured`, `popular_vote`, `genre`)
  VALUES
    ('The Witch', 'New England in the 1630s: William and Katherine lead a devout Christian life with five children, homesteading on the edge of an impassable wilderness. When their newborn son vanishes and crops fail, the family turns on one another. Beyond their worst fears, a supernatural evil lurks in the nearby wood.', 'Robert Eggers', '1397778, 202032, 71083', '/assets/images/posters/f241fdb72bcd96cff6d815e13bccd52adeac107c.jpg', '/assets/images/backdrops/5d8553b661ad96a11668dec1fab5384e5ea54cfc.jpg', 4, 'I have an attraction to the these sorts. Witches, demons, supernatural evil sort of things. But in most cases and I\'m sure most of you will agree with me here when it comes to horror movies its a genre thats been filled up to the brim with terrible low budget movies.\r\n\r\nBut every now and then you find a gem. In comes The Witch. This movie spends its entire time building up to the end. It doesn\'t try and scare you with cheap tricks or jump out and startle you. Instead it opts for one big finale.\r\n\r\nAnd they deliver.\r\n\r\nThe ending will make you uncomfortable, it will make you question what you\'re seeing, and it will linger with you. It\'s a perfect telling of the Devil\'s influence. And how he can destroy everything around you and still have you come crawling.\r\n\r\nHail Satan 666 - go watch this movie.', '2016-02-19', '2016-03-05', NULL, '5', 'Horror')";

    $sample8 = "INSERT INTO `movies` (`movie_title`, `overview`, `director`, `cast`, `poster_path`, `backdrop_path`, `score`, `review`, `release_date`, `publish_date`, `featured`, `popular_vote`, `genre`)
  VALUES
    ('The Revenant', 'In the 1820s, a frontiersman, Hugh Glass, sets out on a path of vengeance against those who left him for dead after a bear mauling.', 'Alejandro Gonzlez Irritu', '6193, 2524, 93491', '/assets/images/posters/f12b701ccc92b53ffadc87dcbce5053c44bd6235.jpg', '/assets/images/backdrops/0283ed0aec45f0c41e56b030ed11d97af693fb10.jpg', 5, 'The Revenant combined a lot of the things I love in life into one movie. Tom Hardy, Leo DiCaprio, survival of the outdoors, intensity in a movie, a darkness over the entire set, struggle, and redemption.\r\n\r\nNot to mention a bear attack scene that was absolutely the most incredibly shot scene I\'ve ever watched. I have a newfound fear of bears.\r\n\r\nThe struggle that not only the actors had to endure but the entire crew. Shooting in that climate and atmosphere, its the love they had for this film that shines through and makes it as good as it is.\r\n\r\nEveryone came to the set ready to go and 100% without a doubt. The story that fuels Leo to push through the climate to reach Hardy. The selfishness that Hardy has for himself that powers his reasoning. It all sets up for a story that shows the true strength a human can endure to get what he wants.\r\n\r\nEven if its vengeance.', '2015-12-25', '2016-03-05', NULL, '7.3', 'Western, Drama, Adventure, Thriller')";

    $sample9 = "INSERT INTO `movies` (`movie_title`, `overview`, `director`, `cast`, `poster_path`, `backdrop_path`, `score`, `review`, `release_date`, `publish_date`, `featured`, `popular_vote`, `genre`)
  VALUES
    ('John Wick', 'After the sudden death of his beloved wife, John Wick receives one last gift from her, a beagle puppy named Daisy, and a note imploring him not to forget how to love. But John\'s mourning is interrupted when his 1969 Boss Mustang catches the eye of sadistic thug Iosef Tarasov who breaks into his house and steals it, beating John unconscious in the process. Unwittingly, he has just reawakened one of the most brutal assassins the underworld has ever known.', 'Chad Stahelski', '6384, 6283, 71586', '/assets/images/posters/06d187a2abcb6a39f2ecb1d813948459b00936de.jpg', '/assets/images/backdrops/c38ebcc610ada89f2a5bf61a4f5aefa2c2d6b85a.jpg', 4, 'This is a movie that jumps right into the action. I\'m a huge fan of Keanu for so many reasons. One of the big reasons is that he does his own stunts, when he takes on a role, especially an action role. He learns everything he can about what he\'s going to need to be for that role.\r\n\r\nDid you know how well he handles a weapon? It\'s ridiculous! The guy can tear up a shooting range no problem. He\'s a big martial arts fan so what you saw in The Matrix, that was real, man.\r\n\r\nI have this theory that they were going to shoot a normal documentary movie about Reeves and so they started following him around with a camera, and thus John Wick ensued.\r\n\r\nThis movie is pure action I mean the total kill count for this movie was 77 at the end. Thats crazy, especially over the course of just a few days!\r\n\r\nYou don\'t fuck with a mans car, you don\'t fuck with a mans dog. End of story.\r\n\r\nHighly anticipating the next one.', '2014-10-22', '2016-03-06', NULL, '7.1', 'Action, Thriller');";
    
    $sample10 = "INSERT INTO `movies` (`movie_title`, `overview`, `director`, `cast`, `poster_path`, `backdrop_path`, `score`, `review`, `release_date`, `publish_date`, `featured`, `popular_vote`, `genre`)
VALUES
	('The Visit', 'The terrifying story of a brother and sister who are sent to their grandparents\' remote Pennsylvania farm for a weeklong trip. Once the children discover that the elderly couple is involved in something deeply disturbing, they see their chances of getting back home are growing smaller every day.', 'M. Night Shyamalan', '1385063, 1198286, 17696', '/assets/images/posters/7c4bc7d0e2202c7d8b8fd98408a29592a94d4014.jpg', '/assets/images/backdrops/c4fa2356e19f7af0034aaa51399accf08f54a10b.jpg', 3, 'A few things really freak me out when they try. Kids and old people in scary movies. The visit has both. Granted the kids aren\'t what\'s scary but if you\'re crawling under a house and your grandma is crawling around extremely crazy and creepy like. Get the fuck out of there.\r\n\r\nM Night has had his share of good movies and bad movies. Some really out there things. But it\'s nice to see he\'s coming back to life with some good movies. \r\n\r\nThe Visit was as strange and startling as it is scary. If you\'ve got a fear of old people this is going to kill it for you!', '2015-09-10', '2016-03-06', NULL, '5.8', 'Horror, Thriller');";
    
    $sample11 = "INSERT INTO `movies` (`movie_title`, `overview`, `director`, `cast`, `poster_path`, `backdrop_path`, `score`, `review`, `release_date`, `publish_date`, `featured`, `popular_vote`, `genre`)
VALUES
	('Spotlight', 'The true story of how The Boston Globe uncovered the massive scandal of child molestation and cover-up within the local Catholic Archdiocese, shaking the entire Catholic Church to its core.', 'Tom McCarthy', '103, 2232, 53714', '/assets/images/posters/14ab8041d7393ab5f6a808063ede63b7e9008775.jpg', '/assets/images/backdrops/8abe841959a58f1f16001d54d00a8cc71da69d7f.jpg', 5, 'I\'ll be honest I hadn\'t even heard of this movie until after the Oscars. With it winning best picture I had to check it out. What a surprise! WHAT A CAST! Wow this movie was on point! How had I not heard of it? It\'s so nice to see a movie fly under the radar and then all of a sudden pop up and be the best.\r\n\r\nThis movie was perfectly paced too. I was interested from the start all the way to the end. It\'s so nice to see a screenplay done so well to capture your attention for the entire movie. Mark Ruffalo really showed a powerful intensity in the entire movie. From his manner towards the subject at the start to consistently rising and rising until you can see it taking a toll on him.\r\n\r\nIt\'s interesting to see how someone can dig deeper into a dark subject and see how it changes them as a person and effects them on a personal level, and in this case, a spiritual level.\r\n\r\nAll in all, wonderful movie, this movie was for me and I couldn\'t have been more gracious to see it win like it did.', '2015-11-06', '2016-03-07 19:59:32', NULL, '7.7', 'Drama, History, Thriller');";

    $run = mysql_query($sample1) or die(mysql_error());
    $run = mysql_query($sample2) or die(mysql_error());
    $run = mysql_query($sample3) or die(mysql_error());
    $run = mysql_query($sample4) or die(mysql_error());
    $run = mysql_query($sample5) or die(mysql_error());
    $run = mysql_query($sample6) or die(mysql_error());
    $run = mysql_query($sample7) or die(mysql_error());
    $run = mysql_query($sample8) or die(mysql_error());
    $run = mysql_query($sample9) or die(mysql_error());
    $run = mysql_query($sample10) or die(mysql_error());
    $run = mysql_query($sample11) or die(mysql_error());
    
    echo "<h1>Movies tables reset</h1>";
  }

  dbSeed()
?>